module.exports = {
  // Auth
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAILED: "LOGIN_FAILED",
  LOGOUT: "LOGOUT",

  // Users
  USER_CREATE: "USER_CREATE",
  USER_UPDATE: "USER_UPDATE",

  // Inventory
  INVENTORY_ADJUST: "INVENTORY_ADJUST",

  // Stock flow
  STOCK_REQUEST_CREATE: "STOCK_REQUEST_CREATE",
  STOCK_REQUEST_DECISION: "STOCK_REQUEST_DECISION",
  STOCK_RELEASE: "STOCK_RELEASE",
  STOCK_RETURN: "STOCK_RETURN",

  // Sales
  SALE_CREATE: "SALE_CREATE",
  SALE_MARK: "SALE_MARK",
  SALE_CANCEL: "SALE_CANCEL",

  // Payments & cash
  PAYMENT_RECORD: "PAYMENT_RECORD",
  CASH_IN: "CASH_IN",
  CASH_OUT: "CASH_OUT",
  VERSEMENT: "VERSEMENT",

  // Credit
  CREDIT_CREATED: "CREDIT_CREATED",
  CREDIT_APPROVE: "CREDIT_APPROVE",
  CREDIT_REJECT: "CREDIT_REJECT",
  CREDIT_SETTLED: "CREDIT_SETTLED"

};
