module.exports = {
  // users
  USER_MANAGE: "USER_MANAGE",
  OWNER_ONLY: "OWNER_ONLY",

  // inventory / requests
  STOCK_REQUEST_CREATE: "STOCK_REQUEST_CREATE",
  STOCK_REQUEST_APPROVE: "STOCK_REQUEST_APPROVE",
  STOCK_RELEASE_TO_SELLER: "STOCK_RELEASE_TO_SELLER",
  STOCK_RETURN_CONFIRM: "STOCK_RETURN_CONFIRM",
  STOCK_REQUEST_VIEW: "STOCK_REQUEST_VIEW",

  // sales
  SALE_CREATE: "SALE_CREATE",
  SALE_MARK_PAID_OR_PENDING: "SALE_MARK_PAID_OR_PENDING",
  SALE_CANCEL: "SALE_CANCEL",
  SALE_VIEW: "SALE_VIEW",

  // credit
  CREDIT_APPROVE: "CREDIT_APPROVE",
  CREDIT_READ: "CREDIT_READ",
  CREDIT_SETTLE: "CREDIT_SETTLE",
  CREDIT_VIEW: "CREDIT_VIEW",

  // payments/cash
  PAYMENT_RECORD: "PAYMENT_RECORD",
  CASH_LEDGER_MANAGE: "CASH_LEDGER_MANAGE",

  // dashboard
  DASHBOARD_OWNER_VIEW: "DASHBOARD_OWNER_VIEW",
  DASHBOARD_VIEW: "DASHBOARD_VIEW",

  // reporting
  REPORT_VIEW: "REPORT_VIEW",

  // audit/messages
  AUDIT_VIEW: "AUDIT_VIEW",
  MESSAGE_CREATE: "MESSAGE_CREATE",

  // products/inventory
  PRODUCT_CREATE: "PRODUCT_CREATE",
  PRODUCT_VIEW: "PRODUCT_VIEW",
  INVENTORY_VIEW: "INVENTORY_VIEW",
  INVENTORY_ADJUST: "INVENTORY_ADJUST",
  INVENTORY_MANAGE: "INVENTORY_MANAGE",

  HOLDINGS_VIEW: "HOLDINGS_VIEW",

  // customers
  CUSTOMER_CREATE: "CUSTOMER_CREATE",
  CUSTOMER_VIEW: "CUSTOMER_VIEW"
};
