// backend/src/permissions/policy.js
const ROLES = require("./roles");
const ACTIONS = require("./actions");

const policy = {
  // Owner: everything
  [ROLES.OWNER]: [...Object.values(ACTIONS)],

  // Admin: full operations (but not OWNER_ONLY)
  [ROLES.ADMIN]: [
    // Core
    ACTIONS.AUTH_ME,
    ACTIONS.DASHBOARD_VIEW,
    ACTIONS.DASHBOARD_OWNER_VIEW,
    ACTIONS.REPORT_VIEW,
    ACTIONS.REPORTS_DOWNLOAD,
    ACTIONS.AUDIT_VIEW,
    ACTIONS.MESSAGE_CREATE,
    ACTIONS.MESSAGE_VIEW,

    // Users / Locations
    ACTIONS.USER_CREATE,
    ACTIONS.USER_VIEW,
    ACTIONS.USER_UPDATE,
    ACTIONS.USER_DELETE,
    ACTIONS.LOCATION_CREATE,
    ACTIONS.LOCATION_VIEW,
    ACTIONS.LOCATION_UPDATE,

    // Products
    ACTIONS.PRODUCT_CREATE,
    ACTIONS.PRODUCT_VIEW,
    ACTIONS.PRODUCT_UPDATE,
    ACTIONS.PRODUCT_PRICE_SET,
    ACTIONS.PRODUCT_PRICING_UPDATE,

    // Inventory
    ACTIONS.INVENTORY_VIEW,
    ACTIONS.INVENTORY_CREATE,
    ACTIONS.INVENTORY_ADJUST,
    ACTIONS.INVENTORY_ARRIVAL_CREATE,
    ACTIONS.INVENTORY_ARRIVAL_VIEW,

    // Inventory adjustment requests
    ACTIONS.INVENTORY_ADJUST_REQUEST_CREATE,
    ACTIONS.INVENTORY_ADJUST_REQUEST_VIEW,
    ACTIONS.INVENTORY_ADJUST_REQUEST_DECIDE,

    // Stock requests
    ACTIONS.STOCK_REQUEST_CREATE,
    ACTIONS.STOCK_REQUEST_VIEW,
    ACTIONS.STOCK_REQUEST_DECIDE,
    ACTIONS.STOCK_RELEASE_CONFIRM,
    ACTIONS.STOCK_RETURN_CONFIRM,

    // Holdings
    ACTIONS.HOLDINGS_VIEW,
    ACTIONS.HOLDINGS_REQUEST_CREATE,
    ACTIONS.HOLDINGS_REQUEST_VIEW,
    ACTIONS.HOLDINGS_REQUEST_DECIDE,

    // Customers
    ACTIONS.CUSTOMER_VIEW,
    ACTIONS.CUSTOMER_CREATE,
    ACTIONS.CUSTOMER_UPDATE,

    // Sales / Payments
    ACTIONS.SALE_CREATE,
    ACTIONS.SALE_VIEW,
    ACTIONS.SALE_MARK,
    ACTIONS.SALE_CANCEL,
    ACTIONS.PAYMENT_RECORD,
    ACTIONS.PAYMENT_VIEW,

    // Credit
    ACTIONS.CREDIT_CREATE,
    ACTIONS.CREDIT_VIEW,
    ACTIONS.CREDIT_DECIDE,

    // Refunds
    ACTIONS.REFUND_CREATE,
    ACTIONS.REFUND_VIEW,

    // Cash / Cashier Ops
    ACTIONS.CASH_SESSION_VIEW,
    ACTIONS.CASH_SESSION_OPEN,
    ACTIONS.CASH_SESSION_CLOSE,
    ACTIONS.CASH_DEPOSIT_VIEW,
    ACTIONS.CASH_DEPOSIT_CREATE,
    ACTIONS.EXPENSE_VIEW,
    ACTIONS.EXPENSE_CREATE,
    ACTIONS.CASH_RECONCILE_VIEW,
    ACTIONS.CASH_RECONCILE_CREATE,
    ACTIONS.CASH_REPORT_VIEW,
  ],

  // Manager: pricing + oversight + approvals
  [ROLES.MANAGER]: [
    // Core
    ACTIONS.AUTH_ME,
    ACTIONS.DASHBOARD_VIEW,
    ACTIONS.REPORT_VIEW,
    ACTIONS.REPORTS_DOWNLOAD,
    ACTIONS.AUDIT_VIEW,
    ACTIONS.MESSAGE_CREATE,
    ACTIONS.MESSAGE_VIEW,

    // Products (pricing control)
    ACTIONS.PRODUCT_VIEW,
    ACTIONS.PRODUCT_UPDATE,
    ACTIONS.PRODUCT_PRICE_SET,
    ACTIONS.PRODUCT_PRICING_UPDATE,
    ACTIONS.PRODUCT_PRICING_MANAGE, // legacy alias safety (maps to PRODUCT_PRICE_SET)

    // Inventory (view + decide requests)
    ACTIONS.INVENTORY_VIEW,
    ACTIONS.INVENTORY_ARRIVAL_VIEW,
    ACTIONS.INVENTORY_ADJUST_REQUEST_VIEW,
    ACTIONS.INVENTORY_ADJUST_REQUEST_DECIDE,

    // Stock requests (decisions)
    ACTIONS.STOCK_REQUEST_VIEW,
    ACTIONS.STOCK_REQUEST_DECIDE,

    // Sales / refunds oversight
    ACTIONS.SALE_VIEW,
    ACTIONS.SALE_CANCEL,
    ACTIONS.REFUND_CREATE,
    ACTIONS.REFUND_VIEW,

    // Payments view
    ACTIONS.PAYMENT_VIEW,

    // Credit decisions
    ACTIONS.CREDIT_VIEW,
    ACTIONS.CREDIT_DECIDE,

    // Cash reporting / recon
    ACTIONS.CASH_REPORT_VIEW,
    ACTIONS.CASH_RECONCILE_VIEW,
    ACTIONS.CASH_RECONCILE_CREATE,
  ],

  // Store keeper: stock + requests + arrivals
  [ROLES.STORE_KEEPER]: [
    // Core
    ACTIONS.AUTH_ME,
    ACTIONS.MESSAGE_CREATE,
    ACTIONS.MESSAGE_VIEW,

    // Products
    ACTIONS.PRODUCT_CREATE,
    ACTIONS.PRODUCT_VIEW,

    // Inventory + arrivals
    ACTIONS.INVENTORY_VIEW,
    ACTIONS.INVENTORY_ARRIVAL_CREATE,
    ACTIONS.INVENTORY_ARRIVAL_VIEW,

    // Inventory adjustment requests (storekeeper creates; manager decides)
    ACTIONS.INVENTORY_ADJUST_REQUEST_CREATE,
    ACTIONS.INVENTORY_ADJUST_REQUEST_VIEW,

    // Stock requests (storekeeper approves/declines)
    ACTIONS.STOCK_REQUEST_VIEW,
    ACTIONS.STOCK_REQUEST_DECIDE,
    ACTIONS.STOCK_RELEASE_CONFIRM,
    ACTIONS.STOCK_RETURN_CONFIRM,

    // Holdings view (optional, but helpful)
    ACTIONS.HOLDINGS_VIEW,
    ACTIONS.STOCK_REQUEST_APPROVE, // add this
    ACTIONS.STOCK_RELEASE_TO_SELLER,
  ],

  // Seller: create sales + request stock
  [ROLES.SELLER]: [
    // Core
    ACTIONS.AUTH_ME,
    ACTIONS.MESSAGE_CREATE,
    ACTIONS.MESSAGE_VIEW,

    // Products + inventory view
    ACTIONS.PRODUCT_VIEW,
    ACTIONS.INVENTORY_VIEW,

    // Stock requests
    ACTIONS.STOCK_REQUEST_CREATE,
    ACTIONS.STOCK_REQUEST_VIEW,

    // Holdings
    ACTIONS.HOLDINGS_VIEW,

    // Customers
    ACTIONS.CUSTOMER_CREATE,
    ACTIONS.CUSTOMER_VIEW,

    // Sales
    ACTIONS.SALE_CREATE,
    ACTIONS.SALE_VIEW,
    ACTIONS.SALE_MARK,

    // Credit (seller can create credit if you want; if not, remove CREDIT_CREATE)
    ACTIONS.CREDIT_CREATE,
    ACTIONS.CREDIT_VIEW,

    // Refund view (seller can see refunds)
    ACTIONS.REFUND_VIEW,
  ],

  // Cashier: money handling + cash session + deposits + expenses
  [ROLES.CASHIER]: [
    // Core
    ACTIONS.AUTH_ME,
    ACTIONS.MESSAGE_CREATE,
    ACTIONS.MESSAGE_VIEW,

    // Sales & customers (view)
    ACTIONS.SALE_VIEW,
    ACTIONS.CUSTOMER_VIEW,
    ACTIONS.PRODUCT_VIEW,

    // Payments
    ACTIONS.PAYMENT_RECORD,
    ACTIONS.PAYMENT_VIEW,

    // Cash sessions (IMPORTANT: OPEN was missing in your file)
    ACTIONS.CASH_SESSION_VIEW,
    ACTIONS.CASH_SESSION_OPEN,
    ACTIONS.CASH_SESSION_CLOSE,

    // Deposits (versement)
    ACTIONS.CASH_DEPOSIT_VIEW,
    ACTIONS.CASH_DEPOSIT_CREATE,

    // Expenses (petty cash)
    ACTIONS.EXPENSE_VIEW,
    ACTIONS.EXPENSE_CREATE,

    // Reconciliation (optional for cashier; if you want manager-only, remove)
    ACTIONS.CASH_RECONCILE_VIEW,
    ACTIONS.CASH_RECONCILE_CREATE,
  ],
};

function can(role, action) {
  const allowed = policy[role] || [];
  return allowed.includes(action);
}

module.exports = { policy, can };
