const ROLES = require("./roles");
const ACTIONS = require("./actions");

const policy = {
  [ROLES.ADMIN]: [
    ...Object.values(ACTIONS)
  ],

  [ROLES.MANAGER]: [
    ACTIONS.SALE_CANCEL,
    ACTIONS.CREDIT_APPROVE,
    ACTIONS.REPORT_VIEW,
    ACTIONS.DASHBOARD_VIEW,
    ACTIONS.AUDIT_VIEW,
    ACTIONS.MESSAGE_CREATE,
    ACTIONS.PRODUCT_VIEW,
    ACTIONS.INVENTORY_VIEW,
    ACTIONS.HOLDINGS_VIEW,
    ACTIONS.CUSTOMER_VIEW,
    ACTIONS.CREDIT_APPROVE,
    ACTIONS.CREDIT_VIEW,
    ACTIONS.SALE_VIEW,
    ACTIONS.CREDIT_READ,
    ACTIONS.STOCK_REQUEST_VIEW,


  ],

  [ROLES.STORE_KEEPER]: [
    ACTIONS.STOCK_REQUEST_APPROVE,
    ACTIONS.STOCK_RELEASE_TO_SELLER,
    ACTIONS.STOCK_RETURN_CONFIRM,
    ACTIONS.MESSAGE_CREATE,
    ACTIONS.PRODUCT_VIEW,
    ACTIONS.INVENTORY_VIEW,
    ACTIONS.INVENTORY_ADJUST,
    ACTIONS.HOLDINGS_VIEW,
    ACTIONS.CREDIT_READ,
    ACTIONS.STOCK_REQUEST_VIEW,

    

  ],

  [ROLES.SELLER]: [
    ACTIONS.STOCK_REQUEST_CREATE,
    ACTIONS.STOCK_REQUEST_VIEW, 
    ACTIONS.SALE_CREATE,
    ACTIONS.SALE_MARK_PAID_OR_PENDING,
    ACTIONS.MESSAGE_CREATE,
    ACTIONS.PRODUCT_VIEW,
    ACTIONS.CUSTOMER_CREATE, 
    ACTIONS.CUSTOMER_VIEW,
    ACTIONS.CREDIT_VIEW,
    ACTIONS.SALE_VIEW,
    ACTIONS.CREDIT_READ,
      ACTIONS.INVENTORY_VIEW

  ],

  [ROLES.CASHIER]: [
    ACTIONS.PAYMENT_RECORD,
    ACTIONS.CASH_LEDGER_MANAGE,
    ACTIONS.MESSAGE_CREATE,
    ACTIONS.PRODUCT_VIEW,
    ACTIONS.CUSTOMER_VIEW,
    ACTIONS.CREDIT_SETTLE,
    ACTIONS.CREDIT_VIEW,
    ACTIONS.SALE_VIEW,
    ACTIONS.CREDIT_READ
  ]
};

function can(role, action) {
  const allowed = policy[role] || [];
  return allowed.includes(action);
}

module.exports = { policy, can };
